"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tokens = void 0;
exports.tokens = {
    colors: {
        primary: '#002d80',
        primaryDark: '#002557',
        primaryLight: '#0052AD',
        secondary: '#00A651',
        secondaryLight: '#4CAF50',
        onPrimary: '#FFFFFF',
        surface: '#FFFFFF',
        background: '#F5F7FA',
        backgroundDark: '#E8EBF0',
        text: '#1A1A1A',
        textSecondary: '#666666',
        textDisabled: '#9E9E9E',
        border: '#E0E0E0',
        borderLight: '#F0F0F0',
        borderDark: '#BDBDBD',
        error: '#F44336',
        success: '#4CAF50',
        warning: '#FF9800',
        info: '#2196F3',
        muted: '#586174',
        accent: '#FFA000',
        cardBg: '#F5F5F6',
        registrationCard: '#EAF7EF',
        selectedOption: '#E8EBF0',
        outgoingBubble: '#EAF0FF',
        outgoingText: '#1B2340',
        infoPanel: '#F6FBFF',
        infoPanelBorder: '#dbeafe',
        warningPanel: '#FDECEC',
        warningPanelBorder: '#f8caca',
        sessionCircle: '#FFF3E0',
    },
    spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, xxl: 48 },
    space: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, xxl: 48 },
    radius: 8,
    radii: { xs: 4, sm: 8, md: 12, lg: 16, xl: 20, pill: 999 },
    fontSizes: {
        xs: 10, sm: 12, md: 14, lg: 16, xl: 18,
        xxl: 20, title: 24, heading: 28, display: 32,
    },
    fontWeights: {
        light: '300',
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
    },
    shadows: {
        small: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 2,
        },
        medium: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.15,
            shadowRadius: 8,
            elevation: 4,
        },
    },
    dimensions: {
        touchTarget: 48,
        inputHeight: 48,
        headerHeight: 60,
        buttonHeights: { small: 36, medium: 48, large: 56 },
        iconSize: { xs: 16, sm: 20, md: 24, lg: 32, xl: 40 },
    },
};
