/** Nombres de los iconos del sistema de diseño. Cada kit de UI dibuja todos. */

export type IconName =
  | 'headset'
  | 'shield-check'
  | 'verified'
  | 'fingerprint'
  | 'face'
  | 'lock-open'
  | 'chevron-left'
  | 'chevron-right'
  | 'transfer'
  | 'card'
  | 'exchange'
  | 'grid'
  | 'home'
  | 'receipt'
  | 'person'
  | 'eye'
  | 'bell'
  | 'savings'
  | 'clock'
  | 'diamond'
  | 'wallet'
  | 'bank'
  | 'donut'
  | 'eye-off'
  | 'arrow-up'
  | 'arrow-down'
  | 'check-circle'
  | 'people'
  | 'close'
  | 'arrow-in'
  | 'arrow-out'
  | 'arrow-forward'
  | 'calendar'
  | 'info'
  | 'document'
  | 'share'
  | 'cloud-off'
  // ─── Detalle de tarjeta de crédito ──────────────────────────────────────
  | 'gift'
  | 'sliders'
  | 'payments'
  | 'pdf'
  | 'download'
  | 'star'
  | 'dashboard'
  | 'block'
  | 'warning'
  | 'event-available'
  | 'calculator'
  // ─── Perfil y oficial de cuenta ─────────────────────────────────────────
  | 'badge'
  | 'mail'
  | 'phone'
  | 'smartphone'
  | 'location'
  | 'devices'
  | 'logout'
  | 'refresh'
  | 'error'
  // ─── Beneficiarios ──────────────────────────────────────────────────────
  | 'person-add'
  | 'globe'
  | 'chevron-down'
  | 'check'
  | 'lock'
  // ─── Seguridad y dispositivos ───────────────────────────────────────────
  | 'key-off'
  | 'password';
