"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BrandHeader = BrandHeader;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_native_1 = require("react-native");
const tokens_1 = require("../../tokens");
const icons_1 = require("../icons");
const styles_1 = require("./styles");
function BrandHeader({ brand, title = 'Asistente', showMenu = true, onMenuPress, showProfile = true, onProfilePress, showNotification = true, onNotificationPress, userInitials = '', hasNotification = true, topInset = 0, }) {
    return ((0, jsx_runtime_1.jsxs)(react_native_1.View, { style: [styles_1.styles.brandHeaderContainer, { paddingTop: 8 + topInset }], children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { style: styles_1.styles.brandLeftSection, children: [showMenu ? ((0, jsx_runtime_1.jsx)(react_native_1.Pressable, { accessibilityRole: "button", accessibilityLabel: "Menu", style: styles_1.styles.brandIconButton, onPress: onMenuPress, children: (0, icons_1.renderFeatherIcon)({ name: 'menu', size: 22, color: tokens_1.tokens.colors.primary }) ?? (0, jsx_runtime_1.jsx)(react_native_1.Text, { style: styles_1.styles.brandMenuIcon, children: "\u2630" }) })) : ((0, jsx_runtime_1.jsx)(react_native_1.View, { style: styles_1.styles.brandIconButton })), brand && (0, jsx_runtime_1.jsx)(react_native_1.View, { style: { width: 28, height: 28, marginLeft: 4, marginRight: 8 }, children: brand }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { style: styles_1.styles.brandTitle, children: title })] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { style: styles_1.styles.brandRightSection, children: [showNotification ? ((0, jsx_runtime_1.jsxs)(react_native_1.Pressable, { accessibilityRole: "button", accessibilityLabel: "Notifications", style: styles_1.styles.brandBellButton, onPress: onNotificationPress, children: [(0, icons_1.renderFeatherIcon)({ name: 'bell', size: 17, color: tokens_1.tokens.colors.text }) ?? (0, jsx_runtime_1.jsx)(react_native_1.Text, { style: styles_1.styles.brandBellIcon, children: "\uD83D\uDD14" }), hasNotification && (0, jsx_runtime_1.jsx)(react_native_1.View, { style: styles_1.styles.brandNotificationDot })] })) : null, showProfile ? ((0, jsx_runtime_1.jsx)(react_native_1.Pressable, { accessibilityRole: "button", accessibilityLabel: "Profile", style: styles_1.styles.brandProfileButton, onPress: onProfilePress, children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { style: styles_1.styles.brandProfileInitials, children: userInitials }) })) : ((0, jsx_runtime_1.jsx)(react_native_1.View, { style: styles_1.styles.brandIconButton }))] })] }));
}
